(()=>{
'use strict';
const C=window.BAHASA_CURRICULUM;
const F=window.BAHASA_FULL_CONTENT;
if(!C||!F) throw new Error('Bahasa AI content data missing');
const KEY='bahasaAI.student.v15';
const DEFAULT={year:1,unit:0,view:'home',xp:0,completed:{},mastery:{},independentEvidence:{},mistakes:[],reviews:[],drafts:{},lastActivity:null};
let state=load();
function load(){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v&&typeof v==='object'?{...DEFAULT,...v}:structuredClone(DEFAULT)}catch{return structuredClone(DEFAULT)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function yearData(){return C.years[state.year]}
function units(){return yearData().units}
function unit(){return units()[Math.max(0,Math.min(state.unit,units().length-1))]}
function rec(){return F.records[unit().id]||F.get?.(unit().id)||{} }
function officialNote(){
 const y=state.year;
 if(y===1)return 'Struktur Tahun 1 dipadankan dengan buku teks Bahasa Melayu SJK; bahan latihan dalam Bahasa AI ialah kandungan asli.';
 if(y===6)return 'Tema dan rangka 24 unit Tahun 6 telah disahkan; tajuk aktiviti Bahasa AI ialah kandungan asli, bukan salinan tajuk buku teks.';
 return 'Kandungan latihan Bahasa AI disusun mengikut perkembangan kemahiran tahun ini. Pemetaan tajuk unit buku teks rasmi masih ditanda berasingan dan tidak didakwa sebagai tajuk rasmi.';
}
const NAV=[['home','🏠','Utama'],['curriculum','📚','Kurikulum'],['learn','🎒','Belajar'],['practice','🎯','Latihan'],['writing','✍️','Karangan'],['review','🔁','Ulang Kaji'],['progress','📈','Kemajuan'],['profile','🙂','Profil']];
function header(){return `<header class="top"><div class="brand"><span class="aira">👩🏻‍🏫</span><div><b>Bahasa <i>AI</i></b><small>Belajar Bahasa Melayu langkah demi langkah</small></div></div><div class="student-pill">Tahun ${state.year} · ⭐ ${state.xp}</div></header><nav class="main-nav">${NAV.map(n=>`<button data-view="${n[0]}" class="${state.view===n[0]?'active':''}"><span>${n[1]}</span>${n[2]}</button>`).join('')}</nav>`}
function shell(body){return `${header()}<main>${body}</main><footer>Bahasa AI · Kandungan pembelajaran asli · Kemajuan aplikasi bukan Tahap Penguasaan rasmi KPM.</footer>`}
function yearButtons(){return `<div class="year-row">${[1,2,3,4,5,6].map(y=>`<button data-year="${y}" class="${state.year===y?'active':''}">Tahun ${y}</button>`).join('')}</div>`}
function home(){const u=unit();return shell(`<section class="hero-card"><div><small>SELAMAT DATANG</small><h1>Hai! Mari belajar bersama Cikgu Aira 👋</h1><p>Pilih tahun, sambung unit semasa, kemudian cuba latihan tanpa petunjuk apabila sudah bersedia.</p>${yearButtons()}<button class="primary" data-view="learn">Sambung ${esc(u.title)} →</button></div><div class="hero-art">🇲🇾<br>🏫</div></section><section class="grid3"><article class="card"><h3>📘 Unit semasa</h3><b class="big">${state.unit+1}/24</b><p>${esc(u.title)}</p></article><article class="card"><h3>⭐ Bukti berdikari</h3><b class="big">${Object.values(state.independentEvidence||{}).filter(n=>n>0).length}</b><p>unit mempunyai percubaan tanpa petunjuk</p></article><article class="card"><h3>🔁 Perlu diulang</h3><b class="big">${dueReviews().length}</b><p>latihan dijadualkan untuk hari ini</p></article></section>`)}
function curriculum(){const us=units();let groups=[];for(let i=0;i<8;i++)groups.push(us.slice(i*3,i*3+3));return shell(`<section class="page"><div class="page-head"><div><small>KURIKULUM TAHUN ${state.year}</small><h1>${esc(yearData().stage)}</h1><p>${esc(yearData().goal)}</p></div>${yearButtons()}</div><div class="source-note">ℹ️ ${esc(officialNote())}</div><div class="themes">${groups.map((g,i)=>`<article class="theme-card"><h2>${g[0]?.theme?.[1]||'📘'} Tema ${i+1}: ${esc(Array.isArray(g[0]?.theme)?g[0].theme[0]:g[0]?.theme||'Pembelajaran')}</h2>${g.map((u,j)=>`<button class="unit-button ${state.unit===i*3+j?'current':''}" data-unit="${i*3+j}"><span>${i*3+j+1}</span><div><b>${esc(u.title)}</b><small>${esc(skillName(u.focus))}</small></div></button>`).join('')}</article>`).join('')}</div></section>`)}
function skillName(id){const s=yearData().skills.find(x=>x[0]===id);return s?.[1]||'Kemahiran Bahasa'}
function contextualSentence(word,r){const rd=(r.readings||[]).find(t=>new RegExp(`\\b${escapeReg(word)}\\b`,'i').test(t));if(!rd)return '';const s=rd.split(/(?<=[.!?])\s+/).find(x=>new RegExp(`\\b${escapeReg(word)}\\b`,'i').test(x));return s||''}
function escapeReg(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function learn(){const u=unit(),r=rec();const read=(r.readings||[])[0]||'';const vocab=(r.vocab||u.words||[]).slice(0,state.year<=2?10:12);return shell(`<section class="page lesson"><div class="breadcrumb"><button data-view="curriculum">← Kurikulum</button><span>Tahun ${state.year} · Unit ${state.unit+1}</span></div><div class="lesson-title"><small>${esc(Array.isArray(u.theme)?u.theme[0]:u.theme||'')}</small><h1>${esc(u.title)}</h1><p>Fokus: <b>${esc(skillName(u.focus))}</b></p></div><div class="learning-path"><span class="on">1 Faham</span><span>2 Belajar</span><span>3 Bina</span><span>4 Guna</span><span>5 Cuba Sendiri</span></div><article class="card reading"><h2>📖 Baca dan faham</h2><p>${esc(read)}</p><button class="secondary" id="speakText">🔊 Dengar bacaan</button></article><article class="card"><h2>🌱 Kosa Kata</h2><div class="vocab-grid">${vocab.map(w=>`<button class="vocab-chip" data-word="${esc(w)}">${esc(w)}</button>`).join('')}</div><div id="vocabContext" class="helper">Tekan perkataan untuk melihat penggunaannya dalam petikan.</div></article><article class="card"><h2>⚙️ Bahasa</h2>${(r.grammar||[]).slice(0,2).map(g=>`<div class="task-row">${esc(g.prompt)}</div>`).join('')||'<p>Aktiviti bahasa akan menggunakan perkataan dan ayat daripada unit ini.</p>'}</article><div class="lesson-actions"><button class="secondary" data-prev>← Unit sebelumnya</button><button class="primary" data-view="practice">Cuba Latihan →</button><button class="secondary" data-next>Unit seterusnya →</button></div></section>`)}
function practiceQuestions(){const r=rec(),reads=r.readings||[];const prompts=[];reads.slice(0,3).forEach((text,i)=>{
 let q;
 if(i===0) q=state.year<=2?'Nyatakan satu perkara yang berlaku dalam petikan.':state.year<=4?'Apakah idea utama petikan ini?':'Nyatakan idea utama dan satu bukti daripada petikan.';
 else if(i===1) q=state.year<=2?'Mengapakah tindakan dalam petikan itu baik atau penting?':state.year<=4?'Apakah yang dapat kamu simpulkan daripada petikan? Berikan sebab.':'Apakah kesimpulan yang boleh dibuat? Sokong dengan bukti.';
 else q=state.year<=2?'Apakah yang akan kamu lakukan dalam situasi yang hampir sama?':'Bagaimanakah idea dalam petikan boleh digunakan dalam situasi baharu? Jelaskan.';
 prompts.push({text,q,kind:i===2?'independent':'guided'});
 });return prompts
}
function practice(){const qs=practiceQuestions();return shell(`<section class="page lesson"><div class="breadcrumb"><button data-view="learn">← Belajar</button><span>${esc(unit().title)}</span></div><div class="lesson-title"><small>LATIHAN</small><h1>🎯 Faham → Fikir → Jawab</h1><p>Jawab dengan perkataan sendiri. Petunjuk hanya untuk latihan berpandu; bukti mastery mesti dibuat tanpa petunjuk.</p></div><div class="practice-list">${qs.map((x,i)=>`<article class="card practice-card"><span class="badge ${x.kind}">${x.kind==='independent'?'Cuba Sendiri':'Latihan '+(i+1)}</span><p class="mini-reading">${esc(x.text)}</p><h2>${esc(x.q)}</h2><textarea id="ans${i}" rows="3" placeholder="Tulis jawapan di sini..."></textarea><div class="practice-actions"><button class="secondary" data-save-answer="${i}" data-kind="${x.kind}">Simpan jawapan</button>${x.kind==='guided'?`<button class="ghost" data-hint="${i}">Petunjuk</button>`:''}</div><div id="fb${i}" class="feedback"></div></article>`).join('')}</div></section>`)}
function writing(){const r=rec(),w=r.writing||{};const saved=state.drafts[unit().id]||'';return shell(`<section class="page lesson"><div class="breadcrumb"><button data-view="learn">← Unit</button><span>Penulisan</span></div><div class="lesson-title"><small>KARANGAN / PENULISAN</small><h1>✍️ Tulis dengan idea sendiri</h1><p>${esc(w.mastery||w.transfer||`Tulis respons tentang ${unit().title}.`)}</p></div><article class="card"><h3>Semak sebelum hantar</h3><div class="checklist">${(w.checklist||['maksud jelas','idea berkaitan','bahasa disemak']).map(x=>`<label><input type="checkbox"> ${esc(x)}</label>`).join('')}</div></article><article class="card"><textarea id="writingText" rows="10" placeholder="Mula menulis di sini...">${esc(saved)}</textarea><div class="writing-bar"><span id="wordCount">0 perkataan</span><button class="secondary" id="saveWriting">Simpan</button><button class="primary" id="submitWriting">Hantar sebagai percubaan berdikari</button></div><div id="writingFeedback" class="feedback"></div></article></section>`)}
function friendlyType(t){const m={guided:'Latihan berpandu',independent:'Cuba sendiri',reading:'Pemahaman',writing:'Penulisan'};return m[t]||'Latihan'}
function dueReviews(){const now=Date.now();return state.reviews.filter(x=>x.due<=now&&!x.done)}
function review(){const due=dueReviews();const recent=state.mistakes.filter(x=>x.year===state.year).slice(-8).reverse();return shell(`<section class="page"><div class="page-head"><div><small>ULANG KAJI</small><h1>🔁 Ulang Kaji Pintar</h1><p>Kesilapan lama kembali pada masa yang sesuai supaya kemahiran tidak cepat lupa.</p></div></div><div class="grid2"><article class="card"><h2>Hari ini</h2><b class="big">${due.length}</b><p>${due.length?'latihan sedia untuk diulang':'Tiada latihan yang perlu diulang hari ini.'}</p>${due.map((x,i)=>`<button class="review-item" data-review="${x.id}">${esc(x.unitTitle)} · ${esc(friendlyType(x.type))}</button>`).join('')}</article><article class="card"><h2>Buku Kesilapan</h2>${recent.length?recent.map(x=>`<div class="mistake"><b>⚠️ ${esc(x.unitTitle)}</b><span>${esc(friendlyType(x.type))}</span><p>${esc(x.prompt)}</p><small>${esc(x.note||'Cuba semula dengan memberi perhatian pada maksud dan kehendak soalan.')}</small></div>`).join(''):'<p>Belum ada kesilapan direkodkan untuk tahun ini.</p>'}</article></div></section>`)}
function progress(){const completed=units().filter(u=>state.completed[u.id]).length,indep=units().filter(u=>(state.independentEvidence?.[u.id]||0)>0).length;return shell(`<section class="page"><div class="page-head"><div><small>KEMAJUAN TAHUN ${state.year}</small><h1>📈 Perjalanan Belajar</h1><p>Latihan berpandu membantu pembelajaran. Percubaan berdikari direkodkan sebagai bukti, tetapi tidak dianggap mastery secara automatik.</p></div>${yearButtons()}</div><div class="grid3"><article class="card"><h3>Unit diteroka</h3><b class="big">${completed}/24</b></article><article class="card"><h3>Bukti berdikari</h3><b class="big">${indep}/24</b></article><article class="card"><h3>Mata pengalaman</h3><b class="big">${state.xp}</b></article></div><div class="unit-progress">${units().map((u,i)=>`<button data-unit="${i}" class="${(state.independentEvidence?.[u.id]||0)>0?'mastered':state.completed[u.id]?'done':''}"><span>${i+1}</span><small>${esc(u.title)}</small></button>`).join('')}</div></section>`)}
function profile(){return shell(`<section class="page"><div class="page-head"><div><small>PROFIL</small><h1>🙂 Ruang Pelajar</h1><p>Tetapan ringkas untuk pembelajaran Bahasa AI.</p></div></div><article class="card"><h2>Tahun semasa</h2>${yearButtons()}</article><article class="card"><h2>Tentang kemajuan</h2><p>Mata pengalaman menunjukkan aktiviti yang telah dibuat. Mastery hanya direkodkan selepas percubaan baharu tanpa petunjuk. Ia bukan Tahap Penguasaan rasmi KPM.</p></article><article class="card danger-zone"><h2>Mulakan semula data versi ini</h2><p>Gunakan hanya jika mahu memadam kemajuan Bahasa AI versi pelajar ini.</p><button class="ghost" id="resetState">Padam kemajuan versi ini</button></article></section>`)}
function render(){const views={home,curriculum,learn,practice,writing,review,progress,profile};$('#app').innerHTML=(views[state.view]||home)();bind();}
function recordMistake(type,prompt,note=''){const x={id:'m'+Date.now()+Math.random(),year:state.year,unitId:unit().id,unitTitle:unit().title,type,prompt,note,at:Date.now()};state.mistakes.push(x);state.reviews.push({id:'r'+Date.now()+Math.random(),year:state.year,unitId:unit().id,unitTitle:unit().title,type,due:Date.now()+86400000,done:false});save()}
function bind(){
 $$('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;save();render();scrollTo(0,0)});
 $$('[data-year]').forEach(b=>b.onclick=()=>{state.year=+b.dataset.year;state.unit=0;state.view=state.view==='home'?'home':'curriculum';save();render()});
 $$('[data-unit]').forEach(b=>b.onclick=()=>{state.unit=+b.dataset.unit;state.view='learn';state.completed[unit().id]=true;state.xp+=2;save();render();scrollTo(0,0)});
 $('[data-prev]')?.addEventListener('click',()=>{if(state.unit>0){state.unit--;save();render();scrollTo(0,0)}});
 $('[data-next]')?.addEventListener('click',()=>{if(state.unit<23){state.unit++;save();render();scrollTo(0,0)}});
 $$('.vocab-chip').forEach(b=>b.onclick=()=>{const s=contextualSentence(b.dataset.word,rec());$('#vocabContext').innerHTML=s?`<b>${esc(b.dataset.word)}</b><br>${esc(s)}`:`<b>${esc(b.dataset.word)}</b><br>Cari perkataan ini dalam bahan unit dan bincangkan maksudnya mengikut konteks.`});
 $('#speakText')?.addEventListener('click',()=>{if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance((rec().readings||[])[0]||'');u.lang='ms-MY';u.rate=.9;speechSynthesis.speak(u)});
 $$('[data-hint]').forEach(b=>b.onclick=()=>{const i=+b.dataset.hint;$('#fb'+i).textContent=state.year<=2?'Petunjuk: cari kata atau tindakan penting dalam petikan.':'Petunjuk: nyatakan idea dahulu, kemudian sokong dengan maklumat daripada petikan.'});
 $$('[data-save-answer]').forEach(b=>b.onclick=()=>{const i=+b.dataset.saveAnswer,v=$('#ans'+i).value.trim(),kind=b.dataset.kind;if(v.length<3){$('#fb'+i).textContent='Tulis jawapan dahulu.';return}state.completed[unit().id]=true;state.xp+=kind==='independent'?5:2;if(kind==='independent'){state.independentEvidence[unit().id]=(state.independentEvidence[unit().id]||0)+1;$('#fb'+i).textContent='⭐ Percubaan berdikari disimpan sebagai bukti. Ia belum dianggap mastery sehingga ketepatan makna dan bahasa disahkan.'}else $('#fb'+i).textContent='✓ Jawapan disimpan sebagai latihan berpandu.';state.lastActivity={unitId:unit().id,kind,at:Date.now()};save()});
 let wt=$('#writingText');if(wt){const count=()=>{$('#wordCount').textContent=(wt.value.trim().match(/\S+/g)||[]).length+' perkataan'};count();wt.oninput=count;$('#saveWriting').onclick=()=>{state.drafts[unit().id]=wt.value;save();$('#writingFeedback').textContent='✓ Draf disimpan.'};$('#submitWriting').onclick=()=>{const n=(wt.value.trim().match(/\S+/g)||[]).length;const min={1:5,2:10,3:20,4:35,5:50,6:70}[state.year];if(n<min){$('#writingFeedback').textContent=`Belum cukup untuk latihan ini. Cuba kembangkan idea kepada sekurang-kurangnya ${min} perkataan.`;recordMistake('writing','Respons penulisan masih terlalu ringkas.','Tambah idea yang relevan, kemudian semak ayat.');return}state.drafts[unit().id]=wt.value;state.completed[unit().id]=true;state.independentEvidence[unit().id]=(state.independentEvidence[unit().id]||0)+1;state.xp+=10;save();$('#writingFeedback').textContent='⭐ Percubaan berdikari disimpan sebagai bukti. Ia tidak dianggap mastery hanya berdasarkan panjang tulisan; semakan makna dan bahasa masih diperlukan.'}}
 $$('[data-review]').forEach(b=>b.onclick=()=>{const x=state.reviews.find(r=>r.id===b.dataset.review);if(x){state.year=x.year;const i=units().findIndex(u=>u.id===x.unitId);if(i>=0)state.unit=i;x.done=true;state.view='practice';save();render();scrollTo(0,0)}});
 $('#resetState')?.addEventListener('click',()=>{if(confirm('Padam semua kemajuan Bahasa AI versi ini?')){state=structuredClone(DEFAULT);save();render()}})
}
window.__BAHASA_V15_TEST__={set:(y,u,v)=>{state.year=y;state.unit=u;state.view=v},html:(v)=>{const fn={home,curriculum,learn,practice,writing,review,progress,profile}[v||state.view]||home;return fn()},unit:()=>unit(),record:()=>rec()};
render();
})();
